version: '3'
# 2つのサービスを設定
services:
  db:
    image: mysql:5.7
    # ローカルのmysql_dataをコンテナのvar/lib/mysqlのフォルダに同期させる(コンテナを落としてもデータを保持させる)
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    # 環境変数の設定
    environment:
      # mysqlのパスワードを設定
      MYSQL_ROOT_PASSWORD: password
  app:
    # いまの直下のdockerfileを参照する
    build: .
    # railsサーバーを起動
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bundle exec puma -C config/puma.rb
    # src以下とapp以下を同期
    volumes:
      - ./src:/app
    # ローカル3000ポートとコンテナの3000番ポートをつなげる
    ports:
      - "3000:3000"
    environment:
      # ワーカーあたりのスレッド数を指定
       RAILS_MAX_THREADS: 5
      # ワーカー数を指定
       WEB_CONCURRENCY: 0
    # dbサービス(mysql)とかんたんにつなげるために書いておく
    depends_on:
      - db
  web:
    build:
      context: containers/nginx
    volumes:
      - ./src/public:/app/public
      - ./src/tmp:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
