version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

# executorを使って実行環境の情報を定義して再利用する
executors:
  # ここに好きな名前で executorを定義できる
  default:
    # このあとのコマンド操作をするディレクトリを指定(CircleCI内のプロジェクト)
    working_directory: ~/kthr01/src
    docker:
      - image: cimg/ruby:2.7.5

jobs:
  build:
    executor: # nameで使いたいexecutorを指定する
      name: default
    steps:
      # ~/kthr01(githubのリポジトリ名)にgitリポジトリ(プロジェクト)をコピー(展開)
      - checkout:
          path: ~/kthr01
      # bundle installなどを実行
      - ruby/install-deps

  test:
    working_directory: ~/kthr01/src
    docker:
      - image: cimg/ruby:2.7.5
      - image: circleci/mysql:8.0
        command: [ --default-authentication-plugin=mysql_native_password ]
        # DBの環境変数を設定(database.ym)
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
    # testジョブ全体の環境変数を設定
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    steps:
      # ~/kthr01(githubのリポジトリ名)にgitリポジトリ(プロジェクト)をコピー(展開)
      - checkout:
          path: ~/kthr01
      # bundle installなどを実行
      - ruby/install-deps

      # mysqlが準備ができるまで待機し、その後処理(mysql起動後にmigrateを実行するため)
      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      # migrateを実行
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      # test
      - run:
          name: Run test
          command: bundle exec rake test
      # brakeman
      - run:
          name: Run brakeman
          command: bundle exec brakeman -A -w1
      # rubocop
      - run:
          name: Run rubocop
          command: bundle exec rubocop

    # EC2にSSH接続し、デプロイを実行
  deploy:
    executor: # nameで使いたいexecutorを指定する
      name: default
    steps:
      - checkout
      # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys:
          fingerprints:
              - "40:8e:0f:c9:3a:db:41:57:af:33:57:76:88:3e:f0:25"
      # CircleCI に登録した環境変数を使ってSSH接続
      - run:
          name: deploy
          command: ssh -o 'StrictHostKeyChecking no' ${USER_NAME}@${HOST_NAME} 'cd && ./release.sh renewal'
          no_output_timeout: 30m

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          # mainブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: main
