version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    working_directory: ~/kthr01/src
    # 実際にやるjobの中身
    steps:
      # ~/kthr01(githubのリポジトリ名)にgitリポジトリをコピーする
      - checkout:
          path: ~/kthr01
      # orbsを使うことで、このような記述ができる。bundle installなどを実行
      - ruby/install-deps

  test:
    # circleciの実行環境
    docker:
      - image: cimg/ruby:2.7.5
      - image: circleci/mysql:5.5
        # DBの環境変数を設定
        # src/config/database.ymlに合わせる
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    # testジョブ全体の環境変数を設定
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    # このあとのコマンド操作をするディレクトリを指定
    working_directory: ~/kthr01/src
    steps:
      # ~/kthr01(githubのリポジトリ名)にgitリポジトリをコピー
      - checkout:
          path: ~/kthr01
      # bundle installなどを実行
      - ruby/install-deps
      # migrateを実行
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      # test
      - run:
          name: test
          command: bundle exec rake test
      # brakeman
      - run:
          name: run brakeman
          command: bundle exec brakeman -A -w1
      # rubocop
      - run:
          name: run rubocop
          command: bundle exec rubocop


# circleciに行わせたいこと（ワークフロー）を書く
workflows:
  # バージョン指定
  version: 2
  # build_and_testという名前のワークフローを作る
  build_and_test:
    # その中のjobsとして、buildを行って,testを行う
    jobs:
      - build
      - test:
          # testを行うためには,buildを行う
          requires:
            - build
