version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    working_directory: ~/kthr01/src
    steps:
      # ~/kthr01(githubのリポジトリ名)にgitリポジトリをコピー
      - checkout:
#          path: ~/kthr01
      # bundle installなどを実行
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:2.7.5
      - image: circleci/mysql:5.5
        # DBの環境変数を設定(database.ym)
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    # testジョブ全体の環境変数を設定
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    # このあとのコマンド操作をするディレクトリを指定
    working_directory: ~/kthr01/src
    steps:
      - checkout:
#          path: ~/kthr01
      # bundle installなどを実行
      - ruby/install-deps
      # migrateを実行
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      # test
      - run:
          name: test
          command: bundle exec rake test
      # brakeman
      - run:
          name: run brakeman
          command: bundle exec brakeman -A -w1
      # rubocop
      - run:
          name: run rubocop
          command: bundle exec rubocop


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
